### ISSUE TITLE
Trying to understand a change

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/fontmake#630] opened 2020-01-23 01:59 UTC
About 3-4 months ago (Oct?Nov? 2019) I used to be able to generate variable font for https://github.com/googlefonts/noto-source/blob/master/src/NotoSerifThai-MM.glyphs , https://github.com/googlefonts/noto-source/blob/master/src/NotoSansThai-MM.glyphs and https://github.com/googlefonts/noto-source/blob/master/src/NotoSansThaiUI-MM.glyphs  (see https://docs.google.com/viewer?url=https%3A%2F%2Fgithub.com%2Fgooglefonts%2Fnoto-fonts%2Fblob%2Fmaster%2FphaseIII_only%2Funhinted%2Fvariable-ttf%2FNotoSansThai-VF.ttf as an example).

Now I get an error
[... not captured ...]
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph roRua-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Regular: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Regular: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Bold: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Light: Glyph ngoNgu-thai, layer Regular: Duplicate glyph layer name
WARNING:glyphsLib.builder.builders.UFOBuilder:Noto Serif Thai Regular: Glyph soSua-thai, layer Regular: Duplicate glyph layer name
Traceback (most recent call last):
  File "/usr/local/google/home/marekj/newrel/noto-source/env/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/usr/local/google/home/marekj/newrel/noto-source/scripts/fontmake/Lib/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/google/home/marekj/newrel/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 670, in run_from_glyphs
    write_skipexportglyphs=write_skipexportglyphs,
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/local/google/home/marekj/newrel/noto-source/scripts/fontmake/Lib/fontmake/font_project.py", line 156, in build_master_ufos
    ufo_module=ufoLib2,
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
    return builder.designspace
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/glyphsLib/builder/builders.py", line 260, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/glyphsLib/builder/builders.py", line 223, in masters
    self.to_ufo_glyph(ufo_glyph, layer, layer.parent)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/glyphsLib/builder/glyph.py", line 123, in to_ufo_glyph
    self.to_ufo_glyph_background(ufo_glyph, layer)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/glyphsLib/builder/glyph.py", line 253, in to_ufo_glyph_background
    new_glyph = ufo_layer.newGlyph(glyph.name)
  File "/usr/local/google/home/marekj/newrel/noto-source/env/lib/python3.7/site-packages/ufoLib2/objects/layer.py", line 120, in newGlyph
    raise KeyError("glyph %r already exists" % name)
KeyError: "glyph 'soSua-thai' already exists"

It appears to me that this is because of the duplicate glyph layer name ... If this is a warning why do I get a KeyError later ... Why did it work before? It appears to me that glyphs.app ignores it and allows me to generate a GX file.

I don't have enough knowledge to issue an opinion either way but I'm trying to understand the change (and raise awareness of the change :-)).

**Comment by punchcutter** [comment] 2020-01-23 02:31
We've always delivered with irrelevant layers removed, but this has a bunch of duplicate layers that aren't used at all. The fun thing is even if I delete all those unused layers it fails with a GPOS error
 `AssertionError: ((1, [2, 1, 1, 1, 2, 1, 1, 1]), 'int', '.LookupCount', 'Feature', '.Feature', 'FeatureRecord', '[0]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')`
I tried every fontmake back to 1.10.1 and nothing is generating the variable font so far. 

Well, I can generate a variable font if I make sure all masters have the same kern pairs even if some are set to zero (Glyphs will generate fine either way). We've seen that issue before, but I thought it wasn't a problem anymore or maybe it's just been so long I thought we fixed it everywhere.

**Comment by marekjez86** [comment] 2020-01-23 04:31
@punchcutter : thanks.... 

Looks to me that there were changes in fontmake over time that caused some of the variable fonts to stop building... One can see it on page https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/variable-ttf (one needs to check the 3-4 months old files there). I should have been building weekly and catching these. Now It's difficult to discern what caused it (I'm certain that we improved something but it could have a been at a cost of something else).

**Comment by anthrotype** [comment] 2020-01-23 15:00
the build error from duplicate glyph layers was supposed to be fixed with glyphsLib v5.1.1 (included with fontmake 2.0.8)
https://github.com/googlefonts/glyphsLib/releases/tag/v5.1.1

but it looks like there are still issues. I'll try to reproduce this when I get the chance.

The second error that @punchcutter reported hints at the master TTFs having different number of lookups for some GPOS feature. If it's one of the auto-generated features, it could be either kern, dist, mark or mkmk.
fontmake has `--debug-feature-file` option which takes a path to a file where to dump the content of the OpenType features generated from ufo2ft featureWriters.
Maybe that could help debugging what's going on.

**Comment by anthrotype** [comment] 2020-01-23 15:07
> Why did it work before?

for the issue with duplicate glyph layers, we were simply assuming they were uniquely named (which in fact they aren't) and unknowingly overwriting layers that had the same name. In UFO, layers must have unique name, in Glyphs.app they are uniquely identified by an UUID and the name can be same. The difference is not easy to reconcile. I would recommend to avoid glyph layers with the same name.

**Comment by anthrotype** [comment] 2020-01-23 15:13
in https://github.com/googlefonts/glyphsLib/pull/570, @moyogo fixed the issue with _foreground_ duplicate glyph layers. The issue that @marekjez86 reported is related but different, in that the glyph layer with duplicate name also have a corresponding _background_ layer. These also need to be de-duplicated to be stored in the UFO.

**Comment by anthrotype** [comment] 2020-01-23 15:42
I see what's going on with the second build error reported by @punchcutter in NotoSerifThai.
With https://github.com/googlefonts/ufo2ft/pull/328, we added support for for un-setting the `ignoreMarks` lookupflag when some kern pairs contain any glyphs that are classified as marks. We basically split the kern lookup in two, a regular one with normal kern pairs and the `ignoreMarks` flag set, and an additional one only containing pairs with some mark glyph (with `ignoreMarks` flag not set; lookupflag applies to the whole lookup, thus we need an additional lookup).
The problem in Noto Serif Thai is that some masters contain some kern pairs against mark glyphs, others do not. This means that some masters will end up with two kern lookups, others with just one, leading to the above error. To merge GPOS tables, varLib expects the same number of lookups. Ufo2ft featureWriters work serially for each master in isolation, without knowledge as to whether the output will be used to build a variable font or a static font...

> I can generate a variable font if I make sure all masters have the same kern pairs even if some are set to zero

it should be sufficient to make sure that all (or none) masters contain pairs that involve mark glyphs. E.g. the Light and CondensedLight masters (when compiled with ufo2ft) end up with this extra kern lookup:

```
lookup kern_ltr_marks {
    pos maiTho-thai.small saraAiMaimalai-thai 30;
    pos maiTho-thai.small saraO-thai 20;
    pos maiTri-thai.small saraAiMaimalai-thai 40;
    pos maiTri-thai.small saraO-thai 40;
} kern_ltr_marks
```

These kern pairs are not present in the other masters, thus the extra lookup without ignoreMarks flag is only generated for Light and CondensedLight, but not for the other ones. I believe it should work if you add 0-value kern pairs for these mark glyphs in the masters where they are missing. This way the consistency between the 8 masters' GPOS tables should be restored.

I know, this is quite annoying, but at the moment I can't find a better solution.

**Comment by punchcutter** [comment] 2020-01-23 15:44
At least on the Serif the kern pairs differ on some masters. So I add those with value of zero and then it works. I have a script to do that. It checks all master keen pairs and makes sure each master has the same pairs.

**Comment by marekjez86** [comment] 2020-01-23 17:45
Great progress on these. Thanks

**Comment by punchcutter** [comment] 2020-01-25 03:54
I ran variable builds on all the standalone Glyphs files and these also failed because of minor kern differences:
NotoSansHebrew.glyphs
NotoSerifTamil-MM.glyphs
NotoSansDisplay-MM.glyphs

**Comment by EbenSorkin** [comment] 2020-05-14 15:40
This issue needs a better title.

**Closed** 2020-05-14 15:44 UTC
