### ISSUE TITLE
Support building of families where not every master has every glyph

### ISSUE THREAD

**Issue by behdad** [googlefonts/fontmake#88] opened 2016-06-10 01:05 UTC
Right now we fail in various ways.  I can provide a family, or it's trivial to create one.

**Comment by anthrotype** [comment] 2017-07-24 17:46
@behdad how would you resolve such incompatibilities?

**Comment by miguelsousa** [comment] 2017-07-24 22:02
I'd like to hear the answer as well. In our [Source Code](https://github.com/adobe-fonts/source-code-pro) family the intermediate master (SourceCodePro_1.ufo) has a subset of the glyphset.

**Comment by behdad** [comment] 2017-08-14 17:17
> I'd like to hear the answer as well.

For gvar, MVAR, etc it's easy: for any quantity, you take all the masters having it and build a variation model for those masters.

For GPOS it's trickier since we rely on the structure of the GPOS table to match across all masters, so it's harder to have sparse intermediate GPOS that, eg, modifies one kern pair only.

**Comment by davelab6** [comment] 2018-11-08 01:18
Has there been any progress on this since August 2017, tracked elsewhere?

**Comment by miguelsousa** [comment] 2018-11-08 05:10
The most recent discussions are here https://github.com/fonttools/fonttools/issues/1355

**Comment by madig** [comment] 2018-11-20 15:37
I can confirm that Behdad's work makes it possible to use sparse UFO masters with just the glyphs you need and turn those into intermediate masters in a VF. It works analogously to what Behdad did in https://github.com/fonttools/fonttools/pull/1368#issuecomment-437257368. If you have e.g. a Thin and a Black master, you can insert a sparse master somewhere in-between with just e.g. an "e", no feature file and an appropriate source entry in the .designspace file, then `fontmake -o ttf-interpolatable` and combine the TTFs with `python3 -m fontTools varLib your.designspace`.

**Comment by behdad** [comment] 2018-11-20 17:00
> I can confirm that Behdad's work makes it possible to use sparse UFO masters with just the glyphs you need and turn those into intermediate masters in a VF. It works like what Behdad did in [fonttools/fonttools#1368 (comment)](https://github.com/fonttools/fonttools/pull/1368#issuecomment-437257368). If you have e.g. a Thin and a Black master, you can insert a sparse master somewhere in-between with just e.g. an "e", no feature file and an appropriate source entry in the .designspace file, then `fontmake -o ttf-interpolatable` and combine the TTFs with `python3 -m fontTools varLib your.designspace`.

Thanks for checking!  I wonder if fontmake from UFO would just work.  Haven't tried.

**Comment by madig** [comment] 2019-08-28 19:56
I suppose we can close this?

**Closed by madig** 2019-08-28 19:56 UTC
