### ISSUE TITLE
name records for platform ID 1

### ISSUE THREAD

**Issue by elitype** [googlefonts/fontmake#796] opened 2021-08-08 17:50 UTC
Hi everyone,
I'm not sure if this is an issue, I noticed when I generate either ttfs or otfs fontmake generates binaries with the name table for platform ID 3 but platform ID 1 is missing. Is there any option to include the mac fields in the name table?
On the other hand, I tried including the openTypeNameRecords in the fontinfo.plist on each of my masters and when I run fontmake it generates the mac name fields but it changes them, for example the Light value is changed to Regular, so now the option is changing the values with ttx or OTMaster but I wonder if there's an easier way to do it.
I also noticed on the google fonts I checked that they only include the platform ID 3 in the name table, is there a reason for this? Thanks in advance.

**Comment by RosaWagner** [comment] 2021-08-09 09:10
Mac names are not included cause useless if you want to match Windows and Mac names. Now if you want mismatched name tables between the 2 platforms, it will create problem in some environments (such as Powerpoint when you want to embed a font in the doc to share it via cloud).

In any case, Google wants to ensure maximum compatibility across all platforms, therefore Name ID 1 and 2 are used as planned by the Opentype spec, ie RIBBI convention. So style name should be Regular, Italic, Bold, Bold Italic. And all styles which are not that should go in family name. Name ID 16 and 17 are the ones that ensure Family and Style names as desired.

Hope it helps :)

**Comment by anthrotype** [comment] 2021-08-09 09:47
+1 what Rosalie said

macOS can read "Windows" (Unicode-ready) names just fine since quite a long time. "Macintosh" names are legacy and only relevant for old Macintosh operating systems (preceding OSX).

**Comment by anthrotype** [comment] 2021-08-09 09:53
duplicate of https://github.com/googlefonts/fontmake/issues/360

**Closed by anthrotype** 2021-08-09 09:53 UTC

**Comment by elitype** [comment] 2021-08-09 12:58
Thank you for clarifying Cosimo and Rosalie!
