### ISSUE TITLE
fontmake stamp on binares

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontmake#782] opened 2021-06-21 16:50 UTC
In order to better triage font bugs, I'd like to write into the sfnt file some stamp of which release version or the git commit of the repo used, so we can say easily "this font was built with fontmake v2.4.0" or "with f9190f1"

**Comment by anthrotype** [comment] 2021-06-21 17:41
closing as duplicate of https://github.com/googlefonts/fontmake/issues/251

**Closed** 2021-06-21 17:45 UTC
