### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by behdad** [googlefonts/fontmake#38] opened 2016-03-01 09:58 UTC
We need to work with maintainers of modules we depend on and clean-up the "dependency hell" we are in right now.  In particular, I'm now stuck with no way to fully utilize the pipeline because of ufolib dep in defcon.  But we all know what problems I'm talking about.  So let's streamline and clean up this together.  Here's my thoughts on how to do it:
- Switch all libraries away from robofab and to defcon and ufolib.  Remove robofab dependency from defcon.  For robofab pens, either move them to fonttools and switch everyone, or make libraries that use robofab pens just make a copy for now.  Deprecate robofab and don't update it anymore and advise everyone to move away from it.
- Switch all uses of plistlib to Python's builtin plistlib.  Defcon master currently seems to do `from ufoLib.plistlib import writePlistToString`, which fails badly if the standalone ufoLib is installed (it doesn't have plistlib).
- Merge all py23 fixes that are outstanding.  Is there any of that left or we're good?  In particular, add the following to every Python source in every library:
  
  `from __future__ import print_function, division, absolute_import`

possibly also:

  `from fontTools.misc.py23 import *`
- Add requirements.txt to all libraries.  Right now fonttools, fontmake, cu2qu, etc have, but since MutatorMath, defcon, etc do NOT, `pip install -U -r requirements.txt` is not as useful as it can be.

If we do the above, it leaves us with just one uncertainty: UFO 2 vs 3.  For that, I suggest that individual modules decided to either support both (in the same branch), or only support UFO 3.  Old versions of libraries that support UFO 2 can live in a branch forever.

So, what do people think?  Can we clean this up please?  If we agree on the action plan?

CC @jamesgk @brawer @adrientetar @anthrotype @typesupply @typemytype @letterror @justvanrossum @moyogo @benkiel

**Comment by adrientetar** [comment] 2016-03-01 10:06
> which fails badly if the standalone ufoLib is installed (it doesn't have plistlib).

Oh yeah I removed the plistlib from ufoLib couple days ago. I can reexport the standard one under ufoLib.plistlib to stay backwards-compatible.

**Comment by adrientetar** [comment] 2016-03-01 10:07
Ok well, I guess I'll get to work upstreaming the defcon changes.

**Comment by behdad** [comment] 2016-03-01 10:10
> Oh yeah I removed the plistlib from ufoLib couple days ago. I can reexport the standard one under ufoLib.plistlib to stay backwards-compatible.

Ouch!  Please unbreak that in the mean time.  Thanks.

**Comment by adrientetar** [comment] 2016-03-01 12:33
I reintroduced plistlib and it serves as py23 shim since public API changed in Python 3.0 and 3.4.

**Comment by behdad** [comment] 2016-03-01 12:37
Thanks!

**Comment by behdad** [comment] 2016-03-01 13:30
Thanks!

On Tue, Mar 1, 2016 at 9:33 PM, Adrien Tétar <notifications@github.com>
wrote:

> I reintroduced plistlib and it serves as py23 shim since public API
> changed in Python 3.0 and 3.4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/fontmake/issues/38#issuecomment-190703972>.
>



-- 
behdad
http://behdad.org/

**Comment by typesupply** [comment] 2016-03-01 19:48
> On Mar 1, 2016, at 4:59 AM, Behdad Esfahbod <notifications@github.com> wrote:
> 
> 	• Switch all libraries away from robofab and to defcon and ufolib. Remove robofab dependency from defcon. For robofab pens, either move them to fonttools and switch everyone, or make libraries that use robofab pens just make a copy for now. Deprecate robofab and don't update it anymore and advise everyone to move away from it.

ALL of RoboFab!? RoboFab is much more than robofab.ufoLib. Yeah, it needs a lot of work but we're trying to get the time to work on that. It's a big project on a list of big projects.

> 	• Switch all uses of plistlib to Python's builtin plistlib. Defcon master currently seems to do from ufoLib.plistlib import writePlistToString, which fails badly if the standalone ufoLib is installed (it doesn't have plistlib).

Defcon master may not work with the independent ufoLib. That ufoLib is UFO 1-3. Defcon master is UFO 1-2. The ufo3 branch of defcon is UFO 1-3.

Tal

**Comment by adrientetar** [comment] 2016-03-01 22:14
> Switch all libraries away from robofab and to defcon and ufolib.

I don't think spec makers and friends(1) will ditch robofab, but we can work with that I think most of the time, libraries aren't very robofab-dependent.

> Deprecate robofab and don't update it anymore and advise everyone to move away from it.

The second point has pretty much happened for quite a while now unless I'm missing something. 
For the rest robofab is what most people in the type scene know and use (it's been around for quite a while, too) and they have scripts and things written with it so asking for deprecation/move away is rather unrealistic, I reckon (it's like asking programmers to stop doing C because there's something new that's better, not gonna happen). Also there are some user-facing changes to going from robofab to defcon mostly robofab has some more abstractions (I don't mean to say that robofab is necessarily easier to use because of it, it just has some differences in its APIs), the difference isn't huge but sufficient to be taken into account when talking deprecation.

> make libraries that use robofab pens just make a copy for now.

Yet's mostly defcon that needs a couple of them, otherwise the base pointPens are in ufoLib now. I think we can work with that too. I know I get along, personally.

If you have specific problems with libs, please raise them here.

> Old versions of libraries that support UFO 2 can live in a branch forever.

If we could have conversion tools like glyphs2ufo generate ufo3 that would be most significant in boosting ufo3 adoption, I reckon. So is a ufo3 font editor but I'm working on that as you know.

Similarly here, I think spec makers and friends(1) won't update unless they have solid reason to, i.e. sufficient part of their tools that uses ufo3 to trigger its adoption. 
Afaict yourself the reason why you considered switching to ufo3 is because MutatorMath requires it.

So in my experience people won't migrate to ufo3 unless you give them a reason to. There are definitely reasons from a developer standpoint to do so just like there are reasons to go from Python 2 to Python 3, that doesn't mean people necessarily feel compelled to do the upgrade. FWIW.

(1): yeah I don't really know how to phrase that but basically the people who have been around using robofab and then UFO since robofont came out

**Comment by typesupply** [comment] 2016-03-01 23:19
> On Mar 1, 2016, at 5:14 PM, Adrien Tétar <notifications@github.com> wrote:
> 
>> Switch all libraries away from robofab and to defcon and ufolib.
> 
> I don't think spec makers and friends(1) will ditch robofab, but we can work with that I think most of the time, libraries aren't very robofab-dependent.

RoboFab has historically been two things:

1. A basic read/write lib for UFOs: ufoLib, glifLib.
2. A scripting API for working inside of a font editing environment. (That can be in a UI or raw object interaction.) glyph = font["A"]

The read/write portion is moving out. I merged the read/write functionality into a submodule years ago and that is now the ufoLib in the official UFO spec library.

The scripting API is the hard part. The current API was cobbled together over a decade ago when we were trying to move into FontLab. The idea of the common API was script portability. For example, when I switched to RoboFont, my scripts from FontLab just worked. I didn't have to rewrite them for a new object model. That has been a HUGE success and there is no way that we're deprecating it. I can't even imagine how many designers use that API in their daily workflow.

What does need to be done with the scripting part is that it needs to be updated to support UFO 3. The existing code is not going to work for that. It's brittle and filled with environment hacks. Our plan is to turn RoboFab into an API documentation and a subclassable base implementation (built on top of defcon). The environment specific implementations (RoboFont, Glyphs, FontLab, etc.) will be up to the developers of the environments. RoboFab will have a way for those environments to  to register their implementations on the fly.

>> Deprecate robofab and don't update it anymore and advise everyone to move away from it.
> 
> The second point has pretty much happened for quite a while now unless I'm missing something. 
> For the rest robofab is what most people in the type scene know and use (it's been around for quite a while, too) and they have scripts and things written with it so asking for deprecation/move away is rather unrealistic, I reckon (it's like asking programmers to stop doing C because there's something new that's better, not gonna happen). Also there are some user-facing changes to going from robofab to defcon mostly robofab has some more abstractions (I don't mean to say that robofab is necessarily easier to use because of it, it just has some differences in its APIs), the difference isn't huge but sufficient to be taken into account when talking deprecation.

Right. RoboFab was designed to be a scripting API. We needed to build some apps and RoboFab was available so we bolted app stuff into it. We quickly realized that app stuff was not very fast. So, I built defcon. Defcon was designed to be a fast base layer with inter-object communication, managed caching and other stuff for apps. It's not a friendly scripting library. It shouldn't be that.

>> Old versions of libraries that support UFO 2 can live in a branch forever.

I agree with this. It's the eventual goal.

> So in my experience people won't migrate to ufo3 unless you give them a reason to. There are definitely reasons from a developer standpoint to do so just like there are reasons to go from Python 2 to Python 3, that doesn't mean people necessarily feel compelled to do the upgrade. FWIW.

RoboFab's API not supporting UFO 3 has been a huge reason for the slow adoption. Most of my libraries have ufo3 branches that are ready.

I absolutely see what you mean about dependency hell though. It's all over the place. I think a good thing to do would be to establish some dependency guidelines or at least chart out what depends on what. That would help us try to get rid of some of the circularity.

If we can get RoboFab + ufoLb resolved I think that would allow the UFO 3 implementations to become the master branches and the current masters could move to a legacy branch. I really want to get the RoboFab stuff done. I just don't have the coding time that I used to. If you want to use a team to get this done, let's draft a plan. (I have more detailed plans for RoboFab somewhere and some volunteers. I've been the problem.) That's probably going to be the fastest way.

Tal

**Comment by adrientetar** [comment] 2016-03-03 10:08
> It's not a friendly scripting library. It shouldn't be that.

I've never got the usability difference, but I haven't used robofab very much either. In any case, I think we all agree that tools should be made on top of defcon.

Would the ufo3 robofab be exactly the same data structures as the previous one? I say this because e.g. [here](https://github.com/googlei18n/ufo2ft/commit/8b69bf69315f2523a025a23eed684425111ab138) we came across a difference between robofab and defcon objects, and if robofab could have the dict syntax here it would simplify things a bit. Overall robofab and defcon objects have good interchangeability, but if checking for discrepencies with defcon objects was one of the goals for this new ufo3 version, that would be convenient. For contours and points the pen protocol abstracts the differences already.

**Comment by typemytype** [comment] 2016-03-03 10:52
Short thing: I can post somewhere how RoboFont uses it. I wrote a wrapper around defcon. This is still UFO2 as there no plan yet how to support the extras from UFO3. 

The main historical difference are segement and the usage of indexes. Those are important for existing scripts m.

I can elaborate when I have more time.

**Comment by typesupply** [comment] 2016-03-03 12:26
FWIW, I've started sketching out the future structure of RoboFab here: https://github.com/robofab-developers/fontParts

**Comment by brawer** [comment] 2017-02-10 13:15
The dependencies are really mind-bogglingly complex today... To reduce dependency hell, how about merging ufoLib into the fonttools codebase as [fontTools.ufoLib](https://github.com/fonttools/fonttools/tree/master/Lib/fontTools)? So many animals in the font zoo depend both on ufoLib and fontTools, so they could as well marry.

**Comment by brawer** [comment] 2017-02-13 10:13
OK, let’s discuss this with the ufoLib folks. Filed https://github.com/unified-font-object/ufoLib/issues/58. Please comment there.

**Comment by benkiel** [comment] 2024-05-02 17:13
This can be closed, we moved ufoLib

**Closed** 2024-05-02 17:21 UTC
