### ISSUE TITLE
OT Feature that "disables" feature variations not working

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/fontmake#950] opened 2022-10-26 23:36 UTC
I have a font that substitute glyphs to get italic shapes based on the axis variation, then I have a feature that disables this replacement.

If the font is built using fontmake, designspace and rules it works as expected on FontGoggles but not Adobe apps, first I thought it was an Adobe issue but I built the font with Glyphs and it works. 

I made a reduced test case using Mutator Sans where it shows S.closed if wght is lower than 500 and added the ss02 to always show default S.

Here both fonts showing correctly on FontGoggles
![imagen](https://user-images.githubusercontent.com/1755590/198158146-1b97572a-e3ca-4936-9244-7b814f4d6535.png)

And the same two fonts showing diferent output on Illustrator. Top is correct.
![imagen](https://user-images.githubusercontent.com/1755590/198157815-70479b89-acb4-48f8-a101-db6e2b2da9bd.png)

I upload a zip file with both fonts and FWIW a ttx dump of GSUB table.
[FeatureVariations+Feature.zip](https://github.com/googlefonts/fontmake/files/9874475/FeatureVariatios%2BFeature.zip)

**Comment by anthrotype** [comment] 2022-10-26 23:50
it looks like Adobe apps do not respect the rule that "rvrn" feature should be applied at the beginning before the rest.

https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt

> It should be processed early in GSUB processing, before application of the localized forms feature or features related to shaping of complex scripts or discretionary typographic effects.

In the font produced by Glyphs.app the lookup for rvrn feature appears before the one for ss02, and thus if application ignores the rvrn comes first rule and applies the lookups in order they appear in the font, you get your desired result.

In the font produced by fontmake, fontTools featureVars always append the lookup for the conditional substitutions at the end of the lookup list, because they rely on the fact that the special 'rvrn' feature tag will prevail and determine the order of application.

In FontGoggles which uses harfbuzz, both fontmake's and Glyphs.app's fonts work. In Adobe apps, according to your report (I haven't confirmed that myself), only the latter works.

**Comment by anthrotype** [comment] 2022-10-26 23:52
I wonder if fontTools featureVars should insert the substution lookup at index 0 when rvrn feature is used to work around this /cc @justvanrossum @behdad

**Comment by khaledhosny** [comment] 2022-10-27 00:01
Which Adobe apps are we talking about specifically? AFAIK, both Photoshop and Illustrator now use HarfBuzz unconditionally.

**Comment by justvanrossum** [comment] 2022-10-27 06:14
(The horrors of `rvrn` never seem to stop.)

(I seem to remember that macOS had the same bug at some point.)

> I wonder if fontTools featureVars should insert the substution lookup at index 0 when rvrn feature is used to work around this

Sure, that would be neat. It's a bit harder to do, as the code will need to remap all subsequent lookup indices.

**Comment by guidoferreyra** [comment] 2022-10-27 17:58
Thanks both for your answers!

**Comment by behdad** [comment] 2022-10-28 17:42
Looks like Apple implementation has the same problem:
https://github.com/fonttools/fonttools/issues/2140

**Comment by anthrotype** [comment] 2022-10-28 17:46
maybe then we should close this as duplicate of #2140 and tackle both there

> remap all subsequent lookup indices

yeah, basically add +1 to lookup list indices in all Feature records and contextual lookups

@behdad would you like to work on that?

**Comment by behdad** [comment] 2022-10-28 18:31
> @behdad would you like to work on that?

Yes I'll take a look. Not sure I can provide tests though.

**Comment by anthrotype** [comment] 2022-10-28 18:44
maybe we can use Guido's test file above 

https://github.com/googlefonts/fontmake/files/9874475/FeatureVariatios%2BFeature.zip

**Comment by behdad** [comment] 2022-10-28 18:59
> maybe we can use Guido's test file above
> 
> https://github.com/googlefonts/fontmake/files/9874475/FeatureVariatios%2BFeature.zip

Test suite already has a test that will be affected by this change, so maybe that's good enough.

**Comment by anthrotype** [comment] 2022-10-28 19:00
ok

**Comment by behdad** [comment] 2022-10-28 19:25
@guidoferreyra Would you be able to rebuild the font with this branch of fonttools and see if that fixes the issue for you:
https://github.com/fonttools/fonttools/pull/2867

**Closed** 2022-10-28 21:45 UTC

**Comment by anthrotype** [comment] 2022-10-28 21:59
Thanks @behdad! 
@guidoferreyra please check this works with your font! And can you please let us know which Adobe app you encountered issue with? Thanks

**Comment by guidoferreyra** [comment] 2022-10-31 14:19
Sorry, just saw the notification now! I will check now.

**Comment by guidoferreyra** [comment] 2022-10-31 14:35
Works for me :)!!
