### ISSUE TITLE
Glyphs Open Corner interpretation not running right

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontmake#649] opened 2020-04-17 11:43 UTC
When using Fontmake to compile a font there is an error on a glyph in the resulting font. It is a shape that uses an Open Corner that has no problem when exporting the font directly from Glyphs.

This is the shape on the source file:

![Screen Shot 2020-04-16 at 21 42 28](https://user-images.githubusercontent.com/48698976/79565369-32808080-8076-11ea-8f22-e6dd772857aa.png)

Resulting glyph in the Fontmake compiled font

![Screen Shot 2020-04-16 at 21 44 49](https://user-images.githubusercontent.com/48698976/79565400-462be700-8076-11ea-9d49-489e07f9636f.png)

![Screen Shot 2020-04-16 at 21 47 42](https://user-images.githubusercontent.com/48698976/79565414-4d52f500-8076-11ea-8550-81d6817f5933.png)

Resulting glyph from when exported directly from Glyphs

![Screen Shot 2020-04-16 at 21 43 48](https://user-images.githubusercontent.com/48698976/79565428-53e16c80-8076-11ea-9c41-58e5a3008d3c.png)

![Screen Shot 2020-04-17 at 06 41 23](https://user-images.githubusercontent.com/48698976/79565512-7f645700-8076-11ea-9b62-6eeb02ce89ff.png)

**Comment by anthrotype** [comment] 2020-04-17 11:52
duplicate of https://github.com/googlefonts/fontmake/issues/288

**Closed by anthrotype** 2020-04-17 11:52 UTC
