### ISSUE TITLE
Error "Expected glyph class definition or statement: got NAME condition"

### ISSUE THREAD

**Issue by HugoJourdan** [googlefonts/fontmake#981] opened 2023-02-19 18:05 UTC
When trying to generate instances, from .glyphs file with :
```
fontmake {path} -o otf  -i
```
I got this error message
```
Compiling UFO failed: instance_ufo/XXX.ufo/features.fea:814:1: Expected glyph class definition or statement: got NAME condition
```

The problem is with the `rlig` feature, if I disable it, the error does not persist.
It's from the condition line, if I take it out, it works.
Here is a screenshot of the problematics lines in .fea file.

<img width="377" alt="Screenshot 2023-02-19 at 19 00 49" src="https://user-images.githubusercontent.com/76793951/219966322-b63c6494-338b-47cd-a564-f078d205ee92.png">

**Comment by anthrotype** [comment] 2023-02-20 10:54
duplicate of https://github.com/googlefonts/fontmake/issues/951

**Closed by anthrotype** 2023-02-20 10:54 UTC
