### ISSUE TITLE
Cannot compile ANY .glyphs file generated with FontLab 7

### ISSUE THREAD

**Issue by cssobral2013** [googlefonts/fontmake#806] opened 2021-09-09 14:59 UTC
Output:
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "SpartanMB-Italic.glyphs" file into <GSFont>
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/fontmake/__main__.py", line 471, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 663, in run_from_glyphs
    designspace_path = self.build_master_ufos(
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontmake/font_project.py", line 142, in build_master_ufos
    font = glyphsLib.GSFont(glyphs_path)
  File "/usr/lib/python3/dist-packages/glyphsLib/classes.py", line 3561, in __init__
    p.parse_into_object(self, fp.read())
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 67, in parse_into_object
    self._fail("Unexpected trailing content", text, i)
  File "/usr/lib/python3/dist-packages/glyphsLib/parser.py", line 235, in _fail
    raise ValueError("{}:\n{}".format(message, text[i : i + 79]))
ValueError: Unexpected trailing content:
;

**Comment by chrissimpkins** [comment] 2021-09-11 11:23
FL 7.2.0.7644 for macOS export that reproduces the issue:

[Tester-Regular.glyphs.zip](https://github.com/googlefonts/fontmake/files/7147659/Tester-Regular.glyphs.zip)

and full glyphs source text of the example font:

<details>
<summary>Glyphs source text</summary>

```
{
familyName = Tester;
customParameters = (
{
name = glyphOrder;
value = (
.notdef,
space
);
}
);
fontMaster = (
{
ascender = 750;
capHeight = 700;
customParameters = (
{
name = typoAscender;
value = 750;
},
{
name = typoDescender;
value = -250;
},
{
name = typoLineGap;
value = 100;
},
{
name = winAscent;
value = 750;
},
{
name = winDescent;
value = 250;
},
{
name = underlineThickness;
value = 50;
},
{
name = underlinePosition;
value = -100;
},
{
name = strikeoutPosition;
value = 300;
},
{
name = strikeoutSize;
value = 50;
},
{
name = subscriptXOffset;
value = 0;
},
{
name = subscriptXSize;
value = 650;
},
{
name = subscriptYOffset;
value = 75;
},
{
name = subscriptYSize;
value = 600;
},
{
name = superscriptXOffset;
value = 0;
},
{
name = superscriptXSize;
value = 650;
},
{
name = superscriptYOffset;
value = 350;
},
{
name = superscriptYSize;
value = 600;
},
{
name = hheaAscender;
value = 750;
},
{
name = hheaDescender;
value = -250;
},
{
name = hheaLineGap;
value = 100;
}
);
descender = -250;
guideLines = (
{
position = "{0, 250}";
}
);
id = "CEDCB468-520A-4792-AC59-2F48859E54AE";
weight = Regular;
widthValue = 100;
weightValue = 100;
xHeight = 500;
}
);
glyphs = (
{
glyphname = .notdef;
},
{
glyphname = space;
layers = (
{
layerId = "CEDCB468-520A-4792-AC59-2F48859E54AE";
width = 260;
}
);
unicode = 0020;
}
);
kerning = {
"CEDCB468-520A-4792-AC59-2F48859E54AE" = {
};
};
unitsPerEm = 1000;
userData = {
GSDimensionPlugin.Dimensions = {
"CEDCB468-520A-4792-AC59-2F48859E54AE" = {
};
};
};
versionMajor = 1;
versionMinor = 0;
};
```

</details>

**Comment by chrissimpkins** [comment] 2021-09-11 11:37
@cssobral2013 Cristiano as a temp workaround, try opening the glyphs file that is exported from FL7 in a text editor and remove the semicolon on the last line, re-save the file with the text editor.  This seems to get fontmake beyond the issue for me.

**Comment by chrissimpkins** [comment] 2021-09-11 11:39
cc @twardoch

**Comment by twardoch** [comment] 2021-09-11 15:14
We’ll look into this. However, if possible, it'd be great if the glyphsLib parser were relaxed a bit, since there are (i.e. will be) FontLab-made .glyphs files around. 

Glyphs.app, FontLab and glyphsLib are three independent implementations of the .glyphs file format. Obviously it’s led by the Glyphs.app implementation, but making parsers _a bit_ more relaxed also helps. It’s a similar situation to the PSD format, I guess. 

FontLab does primarily test roundtrip with Glyphs.app, and Glyphs.app tends to be more relaxed. But we’ll add testing with glyphsLib to the test cycle.

With the version 3 of the .glyphs format we may be a bit more strict because the format itself is more formalized, I think.

**Comment by chrissimpkins** [comment] 2021-09-16 11:49
https://github.com/googlefonts/glyphsLib/pull/719

**Comment by khaledhosny** [comment] 2021-09-28 15:02
Should be fixed with the latest pre-release.

**Closed by khaledhosny** 2021-09-28 15:02 UTC

**Comment by chrissimpkins** [comment] 2021-09-28 15:28
> Should be fixed with the latest pre-release.

thanks Khaled!
